version: '3'

services:

  nginx:
    image: nginx:latest
    container_name: "nginx"
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app

  php:
    build: ..
    container_name: "php"
#    environment:
#      PHP_IDE_CONFIG: "serverName=***"
    volumes:
      - ./:/app
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  db:
    image: postgres:15
    container_name: "postgres"
    environment:
      POSTGRES_DB: "symfony_db"
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit_user
      - RABBITMQ_DEFAULT_PASS=secret
    ports:
      - '5672:5672'
      - '15672:15672'

  redis:
    image: redis:7.0-alpine
    container_name: redis
    restart: unless-stopped
    tty: true
    command: [ "redis-server" ]

volumes:
    ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###